services:
  discord-bot:
    image: mephalrith/soba-bot
    env_file:
      - dev.env
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"